kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-nfs
  namespace: forma-ludo
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
